# Generated by Django 4.1.3 on 2022-11-11 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
