# Generated by Django 4.1.3 on 2022-11-11 22:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_comment_options_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='massage',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
